// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igzzfcdekvofxepgmzlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnenpmY2Rla3ZvZnhlcGdtemx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNTIwNjYsImV4cCI6MjA1NDcyODA2Nn0.NvcgGSUTu7A1RSD59nkm9uxwqv4wx-SN6faS09eCib4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);